export const ARGENTINA_PROVINCES = [
  "Buenos Aires",
  "Ciudad Autónoma de Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
] as const;

export const HOME_CATEGORIES = [
  { icon: "🔧", title: "Hogar y reparaciones", detail: "Plomería, electricidad y electrodomésticos" },
  { icon: "🌿", title: "Campo y exteriores", detail: "Peón, tractorista, terrenos y cercados" },
  { icon: "📦", title: "Mandados y encomiendas", detail: "Compras, trámites, delivery y traslados" },
  { icon: "🚚", title: "Fletes y transporte", detail: "Chofer, camionero, remis y mudanzas" },
  { icon: "❤️", title: "Cuidados y educación", detail: "Niñera, acompañamiento y maestra" },
  { icon: "💼", title: "Empleo local", detail: "Vacantes, changas y perfiles con CV" },
] as const;
