'use strict';
const SUPABASE_URL='https://kjtxkdztssbymtloafrb.supabase.co';
const SUPABASE_KEY='sb_publishable_ZpsIy7fSJK8Ucz6r2DwfZw_UN40LxPR';
const SESSION_KEY='altoque_session_v2';
const state={session:null,user:null,categories:[],posts:[],profile:null,deferredInstall:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3800)}
function loadSession(){try{state.session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{state.session=null}state.user=state.session?.user||null}
function saveSession(data){state.session=data&&data.access_token?data:null;state.user=state.session?.user||null;if(state.session)localStorage.setItem(SESSION_KEY,JSON.stringify(state.session));else localStorage.removeItem(SESSION_KEY)}
function authHeaders(extra={}){return {'apikey':SUPABASE_KEY,'Authorization':`Bearer ${state.session?.access_token||SUPABASE_KEY}`,...extra}}
async function request(path,{method='GET',body,headers={},raw=false}={}){const response=await fetch(SUPABASE_URL+path,{method,headers:authHeaders(headers),body:body==null?undefined:(raw?body:JSON.stringify(body))});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(response.status===401&&state.session?.refresh_token&&!path.includes('/auth/v1/token')){const refreshed=await refreshSession();if(refreshed)return request(path,{method,body,headers,raw})}if(!response.ok){const error=new Error(data?.message||data?.msg||data?.error_description||data?.error||`Error ${response.status}`);error.status=response.status;error.data=data;throw error}return data}
async function refreshSession(){try{const data=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.session.refresh_token})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'Sesión vencida');return d});saveSession(data);return true}catch{saveSession(null);updateAuthUI();return false}}
async function authLogin(email,password){const response=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'No se pudo ingresar');saveSession(data)}
async function authSignup(payload){const response=await fetch(SUPABASE_URL+'/auth/v1/signup',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'No se pudo crear la cuenta');if(data.access_token)saveSession(data);return data}
async function authLogout(){try{if(state.session)await fetch(SUPABASE_URL+'/auth/v1/logout',{method:'POST',headers:authHeaders()})}finally{saveSession(null);state.profile=null;updateAuthUI()}}
async function handleAuthCallback(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));if(hash.get('access_token')){saveSession({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_in:Number(hash.get('expires_in')||3600),token_type:'bearer',user:null});const user=await request('/auth/v1/user');state.session.user=user;state.user=user;saveSession(state.session);history.replaceState({},'',location.pathname);toast('Correo confirmado. Ya podés usar tu cuenta.');return}const query=new URLSearchParams(location.search);if(query.get('token_hash')&&query.get('type')){const response=await fetch(SUPABASE_URL+'/auth/v1/verify',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({token_hash:query.get('token_hash'),type:query.get('type')})});const data=await response.json();if(response.ok&&data.access_token){saveSession(data);history.replaceState({},'',location.pathname);toast('Correo confirmado.')}else if(!response.ok)toast(data.msg||'No se pudo confirmar el correo.',true)}}
function restQuery(table,query=''){return request(`/rest/v1/${table}${query?`?${query}`:''}`)}
function insertRow(table,row){return request(`/rest/v1/${table}`,{method:'POST',body:row,headers:{'Content-Type':'application/json','Prefer':'return=representation'}})}
function updateRows(table,filter,row){return request(`/rest/v1/${table}?${filter}`,{method:'PATCH',body:row,headers:{'Content-Type':'application/json','Prefer':'return=representation'}})}
function rpc(name,args={}){return request(`/rest/v1/rpc/${name}`,{method:'POST',body:args,headers:{'Content-Type':'application/json'}})}
function publicFile(bucket,path){return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function uploadFile(bucket,path,file,upsert=false){const response=await fetch(`${SUPABASE_URL}/storage/v1/object/${bucket}/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:authHeaders({'Content-Type':file.type||'application/octet-stream','x-upsert':String(upsert)}),body:file});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||data?.error||'No se pudo subir el archivo');return data}
function categoryName(id){return state.categories.find(c=>String(c.id)===String(id))?.name||'Oportunidad'}
function categoryIcon(group){const g=(group||'').toLowerCase();if(g.includes('hogar'))return'i-tool';if(g.includes('campo'))return'i-field';if(g.includes('transporte'))return'i-car';if(g.includes('cuidado'))return'i-heart';if(g.includes('belleza'))return'i-star';if(g.includes('empleo'))return'i-work';return'i-list'}
function money(min,max,mode){if(mode==='open'||(min==null&&max==null))return'A convenir';const f=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n));if(min!=null&&max!=null&&Number(min)!==Number(max))return`${f(min)} – ${f(max)}`;return f(min??max)}
function age(date){if(!date)return'';const h=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/36e5));return h<1?'Hace unos minutos':h<24?`Hace ${h} h`:`Hace ${Math.floor(h/24)} d`}
function statusLabel(s){return({open:'Abierta',assigned:'Asignada',completed:'Completada',cancelled:'Cancelada',pending:'Pendiente',accepted:'Aceptada',rejected:'Rechazada',withdrawn:'Retirada'})[s]||s}
function renderEmpty(text){return`<div class="empty">${esc(text)}</div>`}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===view));if(view==='activity')loadActivity();if(view==='profile')loadProfile();window.scrollTo({top:0,behavior:'smooth'})}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
function updateAuthUI(){const logged=!!state.user;$('#authBtn span').textContent=logged?'Mi cuenta':'Ingresar';$('#publishGuest').classList.toggle('hidden',logged);$('#publishForm').classList.toggle('hidden',!logged);$('#activityGuest').classList.toggle('hidden',logged);$('#activityContent').classList.toggle('hidden',!logged);$('#profileGuest').classList.toggle('hidden',logged);$('#profileContent').classList.toggle('hidden',!logged)}
async function validateSession(){loadSession();if(!state.session)return updateAuthUI();try{const user=await request('/auth/v1/user');state.user=user;state.session.user=user;saveSession(state.session)}catch{saveSession(null)}updateAuthUI()}
async function loadCategories(){state.categories=await restQuery('categories','select=*&is_active=eq.true&order=sort_order.asc');const options=state.categories.map(c=>`<option value="${c.id}">${esc(c.group_name)} · ${esc(c.name)}</option>`).join('');$('#publishForm [name=category_id]').innerHTML=options;$('#jobCategory').innerHTML='<option value="">Todas las categorías</option>'+state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');const groups={};state.categories.forEach(c=>(groups[c.group_name]??=[]).push(c));const cards=Object.entries(groups).map(([group,items])=>`<button class="category-card" data-group="${esc(group)}"><span class="cat-icon"><svg><use href="#${categoryIcon(group)}"/></svg></span><b>${esc(group)}</b><small>${items.length} opciones disponibles</small><span class="chips">${items.slice(0,3).map(i=>`<span class="chip">${esc(i.name)}</span>`).join('')}</span></button>`).join('');$('#allGroups').innerHTML=cards;$('#homeGroups').innerHTML=Object.entries(groups).slice(0,6).map(([group,items])=>`<button class="category-card" data-group="${esc(group)}"><span class="cat-icon"><svg><use href="#${categoryIcon(group)}"/></svg></span><b>${esc(group)}</b><small>${items.slice(0,3).map(i=>i.name).join(' · ')}</small></button>`).join('')}
async function loadStats(){try{const stats=await rpc('get_public_stats',{});$('#publicStats').innerHTML=`<strong>${stats.categories??state.categories.length} categorías</strong> · ${stats.open_posts??0} publicaciones abiertas`}catch{$('#publicStats').textContent=`${state.categories.length} categorías disponibles`}}
async function loadPosts(){state.posts=await restQuery('job_posts','select=*&status=eq.open&order=published_at.desc&limit=100');renderPosts();await loadStats()}
