import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createBusiness, createCampaign, setCampaignStatus } from "./actions";

type Business = { id:string; name:string; slug:string; description:string|null; logo_url:string|null; whatsapp:string|null; locality:string|null; province:string|null; is_verified:boolean; is_active:boolean; created_at:string };
type Campaign = { id:string; business_id:string; business_name:string; internal_name:string; placement:string; title:string; body:string|null; status:string; priority:number; starts_at:string; ends_at:string|null; impressions:number; clicks:number; whatsapp:number; coupons:number };
type Dashboard = { businesses:Business[]; campaigns:Campaign[] };
type Category = { id:number; name:string; group_name:string };
const placementLabels:Record<string,string>={top_banner:"Banner superior",contextual_card:"Tarjeta contextual",in_feed:"Entre resultados",wall_note:"Nota del muro",category_sponsor:"Patrocinador de categoría"};

export default async function CommercialAdminPage({searchParams}:{searchParams:Promise<{error?:string;message?:string}>}){
  const messages=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)notFound();const{data:profile}=await supabase.from("profiles").select("is_admin").eq("id",user.id).maybeSingle();if(!profile?.is_admin)notFound();
  const[{data:dashboardData},{data:categoryData}]=await Promise.all([supabase.rpc("admin_commercial_dashboard"),supabase.from("categories").select("id,name,group_name").eq("is_active",true).order("sort_order")]);
  const dashboard=(dashboardData||{businesses:[],campaigns:[]}) as Dashboard;const businesses=dashboard.businesses||[];const campaigns=dashboard.campaigns||[];const categories=(categoryData||[]) as Category[];const groups=[...new Set(categories.map(c=>c.group_name))];const now=new Date();const localDefault=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);
  return <section><div className="appPageTitle"><p className="eyebrow">MONETIZACIÓN LOCAL</p><h1>Comercios y campañas</h1><p>Cargá anunciantes, segmentá espacios y medí resultados.</p></div><div className="adminSectionNav"><Link className="ghostButton" href="/app/admin">Moderación</Link><span className="goldButton">Publicidad</span></div>{messages.error&&<p className="alert error">{messages.error}</p>}{messages.message&&<p className="alert success">{messages.message}</p>}
  <div className="commercialSummary"><article><strong>{businesses.length}</strong><span>Comercios</span></article><article><strong>{campaigns.filter(c=>c.status==="active").length}</strong><span>Campañas activas</span></article><article><strong>{campaigns.reduce((n,c)=>n+Number(c.impressions||0),0)}</strong><span>Impresiones</span></article><article><strong>{campaigns.reduce((n,c)=>n+Number(c.clicks||0)+Number(c.whatsapp||0),0)}</strong><span>Interacciones</span></article></div>
  <details className="commercialEditor" open={businesses.length===0}><summary>Agregar comercio</summary><form action={createBusiness} className="premiumForm"><div className="formGrid"><label>Nombre<input name="name" required minLength={2} maxLength={100}/></label><label>Identificador<input name="slug" required placeholder="pintureria-central" pattern="[a-z0-9-]+"/></label><label>WhatsApp<input name="whatsapp" placeholder="+54 9 2302..."/></label><label>Logo por URL<input name="logoUrl" type="url" placeholder="https://..."/></label><label>Provincia<input name="province" defaultValue="La Pampa"/></label><label>Localidad<input name="locality" defaultValue="Ingeniero Luiggi"/></label></div><label>Descripción<textarea name="description" maxLength={1200}/></label><div className="checkRow"><label><input type="checkbox" name="isActive" defaultChecked/> Comercio activo</label><label><input type="checkbox" name="isVerified"/> Comercio verificado</label></div><button className="primaryButton">Crear comercio</button></form></details>
  <div className="sectionTitle spaced"><div><h2>Comercios cargados</h2><p>Base disponible para campañas.</p></div></div><div className="businessAdminGrid">{businesses.length?businesses.map(b=><article key={b.id}><span className="sponsoredLabel">{b.is_active?"ACTIVO":"INACTIVO"}</span><h3>{b.name}</h3><p>{b.description||"Sin descripción."}</p><small>{[b.locality,b.province].filter(Boolean).join(", ")||"Sin ubicación"}</small>{b.is_verified&&<b>Verificado</b>}</article>):<div className="emptyState"><h3>No hay comercios</h3><p>Creá el primero para habilitar campañas.</p></div>}</div>
  {businesses.length>0&&<details className="commercialEditor"><summary>Crear campaña publicitaria</summary><form action={createCampaign} className="premiumForm"><div className="formGrid"><label>Comercio<select name="businessId" required>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Nombre interno<input name="internalName" required placeholder="Pintura agosto"/></label><label>Espacio<select name="placement" defaultValue="contextual_card">{Object.entries(placementLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Estado<select name="status" defaultValue="draft"><option value="draft">Borrador</option><option value="pending">Pendiente</option><option value="active">Activa</option><option value="paused">Pausada</option><option value="ended">Finalizada</option></select></label><label>Título<input name="title" required minLength={3} maxLength={120}/></label><label>Texto del botón<input name="ctaLabel" placeholder="Ver oferta" maxLength={40}/></label><label>URL / WhatsApp<input name="ctaUrl" type="url" placeholder="https://wa.me/..."/></label><label>Cupón<input name="couponCode" maxLength={40}/></label><label>Categoría<select name="categoryId" defaultValue=""><option value="">Todas</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Grupo<select name="groupName" defaultValue=""><option value="">Todos</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Provincia<input name="province" defaultValue="La Pampa"/></label><label>Localidad<input name="locality" defaultValue="Ingeniero Luiggi"/></label><label>Prioridad<input name="priority" type="number" min="0" max="100" defaultValue="50"/></label><label>Comienza<input name="startsAt" type="datetime-local" defaultValue={localDefault}/></label><label>Finaliza<input name="endsAt" type="datetime-local"/></label></div><label>Descripción<textarea name="body" maxLength={320}/></label><button className="goldButton">Crear campaña</button></form></details>}
  <div className="sectionTitle spaced"><div><h2>Campañas</h2><p>Visibilidad y resultados por anuncio.</p></div></div><div className="campaignAdminList">{campaigns.length?campaigns.map(c=><article key={c.id}><header><div><span className="sponsoredLabel">{placementLabels[c.placement]||c.placement}</span><h3>{c.title}</h3><small>{c.business_name} · prioridad {c.priority}</small></div><span className={`statusBadge ${c.status}`}>{c.status}</span></header><p>{c.body||"Sin descripción."}</p><div className="campaignMetrics"><span><strong>{c.impressions||0}</strong> impresiones</span><span><strong>{c.clicks||0}</strong> clics</span><span><strong>{c.whatsapp||0}</strong> WhatsApp</span><span><strong>{c.coupons||0}</strong> cupones</span></div><div className="campaignStatusActions">{c.status!=="active"&&<form action={setCampaignStatus}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="active"/><button className="primaryButton small">Activar</button></form>}{c.status!=="paused"&&<form action={setCampaignStatus}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="paused"/><button className="ghostButton">Pausar</button></form>}{c.status!=="ended"&&<form action={setCampaignStatus}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="ended"/><button className="dangerButton">Finalizar</button></form>}</div></article>):<div className="emptyState"><h3>No hay campañas</h3><p>Los espacios permanecen ocultos hasta crear y activar una.</p></div>}</div></section>;
}
